version: "3"
services:
  timeslots:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: timeslots_service
    environment:
      - TG_TOKEN=${TG_TOKEN}
    ports:
      - "8080:8080"